export const INPUT_SUCCESS = "INPUT_SUCCESS";
export const INPUT_FAILURE = "INPUT_FAILURE";
export const SESSION_SUCCESS = "SESSION_SUCCESS";
export const SESSION_END = "SESSION_END";
export const SESSION_FAILURE = "SESSION_FAILURE";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_FAILURE = "MESSAGE_FAILURE";